# Generated by Django 3.0.5 on 2020-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ride',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pickUp', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('complete', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('cost', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
