# Generated by Django 3.0.5 on 2020-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20200427_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driverId',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
