# Generated by Django 3.0.6 on 2020-05-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_auto_20200505_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='expectedTime',
            field=models.CharField(default='inf', max_length=200),
        ),
    ]
