# Generated by Django 3.0.5 on 2020-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
